//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class activation
{
    public int id { get; set; }
    public System.Guid activatioin_code { get; set; }

    public virtual sign_up sign_up { get; set; }
}

public partial class hackers_choice
{
    public string tumi { get; set; }
    public string passwd { get; set; }
}

public partial class sign_up
{
    public int id { get; set; }
    public string firstname { get; set; }
    public string lastname { get; set; }
    public string username { get; set; }
    public string password { get; set; }
    public string email { get; set; }
    public Nullable<System.DateTime> creation_date { get; set; }
    public string folder_path { get; set; }

    public virtual activation activation { get; set; }
}
